name: Project Status

on:
  push:
    branches: [ main, master ] # Hangi branch'e push yapınca güncellensin?

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Status Check
        run: echo "Last commit registered successfully."
